// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChargesUIClient is the client API for ChargesUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChargesUIClient interface {
	// ListEngineSpecs returns a list of Charging Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ChargesUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type chargesUIClient struct {
	cc grpc.ClientConnInterface
}

func NewChargesUIClient(cc grpc.ClientConnInterface) ChargesUIClient {
	return &chargesUIClient{cc}
}

func (c *chargesUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ChargesUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChargesUI_ServiceDesc.Streams[0], "/v1.ChargesUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &chargesUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChargesUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type chargesUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *chargesUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chargesUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ChargesUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChargesUIServer is the server API for ChargesUI service.
// All implementations must embed UnimplementedChargesUIServer
// for forward compatibility
type ChargesUIServer interface {
	// ListEngineSpecs returns a list of Charging Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, ChargesUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedChargesUIServer()
}

// UnimplementedChargesUIServer must be embedded to have forward compatible implementations.
type UnimplementedChargesUIServer struct {
}

func (UnimplementedChargesUIServer) ListEngineSpecs(*ListEngineSpecsRequest, ChargesUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedChargesUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedChargesUIServer) mustEmbedUnimplementedChargesUIServer() {}

// UnsafeChargesUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChargesUIServer will
// result in compilation errors.
type UnsafeChargesUIServer interface {
	mustEmbedUnimplementedChargesUIServer()
}

func RegisterChargesUIServer(s grpc.ServiceRegistrar, srv ChargesUIServer) {
	s.RegisterService(&ChargesUI_ServiceDesc, srv)
}

func _ChargesUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChargesUIServer).ListEngineSpecs(m, &chargesUIListEngineSpecsServer{stream})
}

type ChargesUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type chargesUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *chargesUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ChargesUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChargesUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ChargesUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChargesUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChargesUI_ServiceDesc is the grpc.ServiceDesc for ChargesUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChargesUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ChargesUI",
	HandlerType: (*ChargesUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ChargesUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _ChargesUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "charges-ui.proto",
}
